added hover tool, sd selector, log normal masses prior
ML4GW/BBHNet pull request #263
Opened 2023-01-27 14:24 UTC by rafia17

2023-01-27 15:35 UTC, EthanMarx commented
Nice work. It looks like you don't have the pre-commit hooks installed. See [here](https://github.com/ML4GW/BBHNet/blob/main/CONTRIBUTING.md#pre-commit-hooks) in the contributing.md file for instructions on how to install those. Once installed, you should be able to run `pre-commit run --all-files` and then re-commit

2023-01-27 16:43 UTC, rafia17 commented
Hi there!

I have run all pre-commit checks and everything looks fine at my end. Not
sure what next to do in this pull request to have it merge. I think you
might need to approve or something.

Thanks
Rafia

On Fri, Jan 27, 2023 at 9:35 AM Ethan Marx ***@***.***> wrote:

> Nice work. It looks like you don't have the pre-commit hooks installed.
> See here
> <https://github.com/ML4GW/BBHNet/blob/main/CONTRIBUTING.md#pre-commit-hooks>
> in the contributing.md file for instructions on how to install those. Once
> installed, you should be able to run pre-commit run --all-files and then
> re-commit
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ML4GW/BBHNet/pull/263#issuecomment-1406666459>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANHQOK5LH3R247YI33GT7L3WUPTLTANCNFSM6AAAAAAUIYFWBQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-27 17:27 UTC, EthanMarx requested changes

2023-01-30 12:44 UTC, rafia17 commented on projects/sandbox/vizapp/vizapp/plots/vt.py
>          self.figure.extra_y_ranges["n_eff"].end = 2 * n_eff.max()
Yes. I have removed those and pushed the changes to the branch.

2023-01-30 12:45 UTC, rafia17 commented on projects/sandbox/vizapp/vizapp/plots/vt.py
>          self.figure.extra_y_ranges["n_eff"].end = 2 * n_eff.max()
Yes, I have removed those and pushed changes to the branch

2023-01-31 16:04 UTC, EthanMarx approved these changes

2023-01-31 18:45 UTC, merged